### PR TITLE
Fix build issue with Android Studio and jackson jar missing file

### PR DESCRIPTION
**Pull request by smart-fun**
Fix build issue with Android Studio: replaced missing com.fasterxml.jackson.core.jar file with a remote repository dependency.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@smart-fun__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by jofriedm-msft** [comment]
Hi @smart-fun, this was done purposely. That jar is only needed for table operations and to reduce the size of the library for customers not using tables, that jar is not included by default. Please let me know if you have any further questions or concerns.

Thanks!

**Comment by smart-fun** [comment]
Thank you for your answer. I understand your point of view. In my opinion this is too bad I cannot reference your library directly from my project because it does not compile. So I had to fork your library and fix it so that I can now use it remotely. This is quite unusual to me to deliver something that does not compile. Anyway I have a solution ;)

**Comment by mirobers** [comment]
Hey @smart-fun, although you have found a solution to your problem you might want to check out the [usage readme](https://github.com/Azure/azure-storage-android#usage) if you haven't already.

> If using Maven or Gradle, Jackson-Core should be automatically added to the build path. Otherwise, please download the jar and add it to your build path. Also, please make sure that the jar will be added to your project's apk. To do this in Eclipse, right click your project, select "Build Path->Configure Build Path", navigate to the "Order and Export" tab and check the box next to the jackson-core jar.

**Comment by jofriedm-msft** [comment]
Leave a comment

**Comment by azurecla** [comment]
Hi __@smart-fun__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by jofriedm-msft** [comment]
Hi @smart-fun , I was wrong with my initial statement. I re-examined how we were doing things in master with eclipse and we are getting the jar remotely. Your changes look good. I will also make the changes to the test build.gradle to get the jars remotely. Thanks!

**Comment by smart-fun** [comment]
Thanks for having merged my pull request. Could you please tell me when you do a release with that change so that I can use your repository with my project? (I'll check sometimes anyway) Thanks!

**Comment by jofriedm-msft** [comment]
Sure, there will be changes to support the new REST version which should be released at the end of the month. Those changes along with the support of Android Studio will also be brought to master.

**Pull request merged**
